name: SimplePipline

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Insatalling Dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Runing Linting tests"
          npm run lint
        env:
          CI: true
  
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checking Security
        run: |
          echo "Running Security Checks"
          sleep 5s;
          echo "Running Security Checks 1"
          sleep 5s;
          echo "Running Security Checks 2"
          sleep 5s;
  buildApp:
    name: Build App
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - name: Building App
        run: |
          echo "Running Build"
          npm run build
